name: Test & Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Set up GoLang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.1'
    
    - name: Run Go Tests
      run: go test -v
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable
    
    # - name: Packer Build
    #   run: |
    #     go get -u github.com/gobuffalo/packr/packr
    #     GOOS=linux GOARCH=amd64 packr build
